spring:
#  mvc:
#改变静态资源访问路径   shift+f9 刷新浏览器页面   //会导致欢迎页面失效,导致favicon.ico失效
#    static-path-pattern: /hu/**
#改变静态资源存放目录
#  resources:
#    static-locations: classpath:/Hu
  mvc:
    hiddenmethod:
      filter:
        enabled: true